#!/usr/bin/env python3
"""
EMsoft EBSD Pattern Visualizer
=============================
Visualizes synthetic EBSD patterns generated by the EMsoft pipeline.
Produces grid views, single-pattern details, intensity profiles, and TIFF exports.

Usage:
    python visualize.py                           # run all visualizations
    python visualize.py --grid                    # grid of all patterns
    python visualize.py --single 0                # single pattern with profiles
    python visualize.py --export-tiff             # export as TIFF images
    python visualize.py --compare                # compare patterns side-by-side
    python visualize.py --heatmap                # pixel-wise mean/std heatmap
"""

import argparse
import os
import sys

import h5py
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from load_data import EBSDDataLoader


def plot_grid(loader, output_path=None, cols=None, cmap='gray'):
    """
    Plot all patterns in a grid with Euler angle labels.

    Args:
        loader: EBSDDataLoader instance
        output_path: path to save the figure (optional)
        cols: number of columns (auto if None)
        cmap: colormap
    """
    patterns = loader.patterns
    euler = loader.euler_angles
    n = patterns.shape[0]

    if cols is None:
        cols = min(5, n)
    rows = int(np.ceil(n / cols))

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3.5, rows * 3.2))
    if rows == 1 and cols == 1:
        axes = np.array([axes])
    axes = axes.flatten()

    vmin = patterns.min()
    vmax = patterns.max()
    im = None

    for i in range(n):
        ax = axes[i]
        im = ax.imshow(patterns[i], cmap=cmap, origin='lower', vmin=vmin, vmax=vmax)
        e = euler[i]
        ax.set_title(f'#{i+1}\nφ₁={e[0]:.1f}° φ₂={e[1]:.1f}° φ₃={e[2]:.1f}°', fontsize=7)
        ax.axis('off')

    for i in range(n, len(axes)):
        axes[i].axis('off')

    if im is not None:
        plt.colorbar(im, ax=axes, shrink=0.5, label='Intensity')
    title = f'Synthetic EBSD Patterns — {loader.crystal_name} ({n} patterns, {loader.pattern_shape[0]}×{loader.pattern_shape[1]} px)'
    fig.suptitle(title, fontsize=12, y=1.02)

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f'[OK] Saved: {output_path}')
    plt.show()
    plt.close(fig)


def plot_single_with_profiles(loader, idx=0, output_path=None):
    """
    Plot a single pattern with horizontal and vertical intensity profiles.

    Args:
        loader: EBSDDataLoader instance
        idx: pattern index (0-based)
        output_path: path to save the figure (optional)
    """
    pat = loader.patterns[idx]
    euler = loader.euler_angles[idx]

    fig, axes = plt.subplots(1, 3, figsize=(14, 4),
                               gridspec_kw={'width_ratios': [1.2, 1, 1]})

    im = axes[0].imshow(pat, cmap='gray', origin='lower')
    axes[0].set_title(f'Pattern #{idx+1}\nφ₁={euler[0]:.1f}° φ₂={euler[1]:.1f}° φ₃={euler[2]:.1f}°')
    axes[0].axis('off')
    plt.colorbar(im, ax=axes[0], shrink=0.8, label='Intensity')

    row = pat.shape[0] // 2
    axes[1].plot(pat[row, :], 'k-', lw=0.8)
    axes[1].axvline(row, color='r', lw=1, ls='--', alpha=0.7)
    axes[1].set_title(f'Horizontal profile\n(row {row})')
    axes[1].set_xlabel('Column (px)')
    axes[1].set_ylabel('Intensity')
    axes[1].grid(True, alpha=0.3)

    col = pat.shape[1] // 2
    axes[2].plot(pat[:, col], 'k-', lw=0.8)
    axes[2].axvline(col, color='r', lw=1, ls='--', alpha=0.7)
    axes[2].set_title(f'Vertical profile\n(col {col})')
    axes[2].set_xlabel('Row (px)')
    axes[2].set_ylabel('Intensity')
    axes[2].grid(True, alpha=0.3)

    fig.suptitle(f'EBSD Pattern — {loader.crystal_name}', fontsize=12)
    plt.tight_layout()

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f'[OK] Saved: {output_path}')
    plt.show()
    plt.close(fig)


def plot_pattern_difference(loader, idx1=0, idx2=1, output_path=None):
    """
    Show two patterns and their absolute difference.
    Useful for seeing how strain/orientation changes affect the pattern.
    """
    p1 = loader.patterns[idx1]
    p2 = loader.patterns[idx2]

    diff = np.abs(p2 - p1)

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))

    vmin = loader.patterns.min()
    vmax = loader.patterns.max()

    axes[0].imshow(p1, cmap='gray', origin='lower', vmin=vmin, vmax=vmax)
    axes[0].set_title(f'Pattern #{idx1+1}\n{loader.euler_angles[idx1].round(1)}')
    axes[0].axis('off')

    axes[1].imshow(p2, cmap='gray', origin='lower', vmin=vmin, vmax=vmax)
    axes[1].set_title(f'Pattern #{idx2+1}\n{loader.euler_angles[idx2].round(1)}')
    axes[1].axis('off')

    im = axes[2].imshow(diff, cmap='hot', origin='lower')
    axes[2].set_title(f'|P{idx2+1} − P{idx1+1}|\nmax={diff.max():.4f}')
    axes[2].axis('off')
    plt.colorbar(im, ax=axes[2], shrink=0.8, label='|Difference|')

    fig.suptitle('Pattern Comparison', fontsize=12)
    plt.tight_layout()

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f'[OK] Saved: {output_path}')
    plt.show()
    plt.close(fig)


def plot_pixel_statistics(loader, output_path=None):
    """
    Plot per-pixel mean and standard deviation across all patterns.
    Shows which regions of the detector are most sensitive to orientation/strain.
    """
    patterns = loader.patterns

    mean_map = patterns.mean(axis=0)
    std_map = patterns.std(axis=0)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    vmin_m = mean_map.min()
    vmax_m = mean_map.max()
    im0 = axes[0].imshow(mean_map, cmap='viridis', origin='lower', vmin=vmin_m, vmax=vmax_m)
    axes[0].set_title('Mean intensity per pixel')
    axes[0].axis('off')
    plt.colorbar(im0, ax=axes[0], shrink=0.8, label='Mean intensity')

    vmin_s = std_map.min()
    vmax_s = std_map.max()
    im1 = axes[1].imshow(std_map, cmap='plasma', origin='lower', vmin=vmin_s, vmax=vmax_s)
    axes[1].set_title('Std dev per pixel (sensitivity map)')
    axes[1].axis('off')
    plt.colorbar(im1, ax=axes[1], shrink=0.8, label='Std dev')

    fig.suptitle(f'Pixel Statistics ({patterns.shape[0]} patterns)', fontsize=12)
    plt.tight_layout()

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f'[OK] Saved: {output_path}')
    plt.show()
    plt.close(fig)


def plot_intensity_histogram(loader, output_path=None):
    """
    Plot intensity distribution across all patterns.
    """
    patterns = loader.patterns

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].hist(patterns.ravel(), bins=100, color='steelblue', edgecolor='none', alpha=0.8)
    axes[0].set_xlabel('Pixel intensity')
    axes[0].set_ylabel('Count')
    axes[0].set_title('Intensity histogram (all patterns)')
    axes[0].grid(True, alpha=0.3)

    for i in range(min(9, patterns.shape[0])):
        axes[1].hist(patterns[i].ravel(), bins=50, alpha=0.5, label=f'#{i+1}')
    axes[1].set_xlabel('Pixel intensity')
    axes[1].set_ylabel('Count')
    axes[1].set_title('Intensity histogram (per pattern)')
    axes[1].legend(fontsize=7)
    axes[1].grid(True, alpha=0.3)

    fig.suptitle(f'Intensity Distribution — {loader.crystal_name}', fontsize=12)
    plt.tight_layout()

    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f'[OK] Saved: {output_path}')
    plt.show()
    plt.close(fig)


def export_as_tiff(loader, output_dir):
    """
    Export each pattern as a grayscale TIFF image.
    """
    os.makedirs(output_dir, exist_ok=True)
    patterns = loader.patterns

    for i in range(patterns.shape[0]):
        pat = patterns[i]
        pat_norm = ((pat - pat.min()) / (pat.max() - pat.min()) * 255).astype(np.uint8)
        img = Image.fromarray(pat_norm, mode='L')
        path = os.path.join(output_dir, f'pattern_{i+1:06d}.tiff')
        img.save(path, compression='tiff_deflate')

    print(f'[OK] Exported {patterns.shape[0]} TIFF images to: {output_dir}/')


def export_as_png(loader, output_dir):
    """
    Export each pattern as a PNG image.
    """
    os.makedirs(output_dir, exist_ok=True)
    patterns = loader.patterns
    euler = loader.euler_angles

    for i in range(patterns.shape[0]):
        fig, ax = plt.subplots(figsize=(6.4, 4.8))
        ax.imshow(patterns[i], cmap='gray', origin='lower')
        e = euler[i]
        ax.set_title(f'Pattern #{i+1}\nφ₁={e[0]:.1f}° φ₂={e[1]:.1f}° φ₃={e[2]:.1f}°', fontsize=9)
        ax.axis('off')
        plt.tight_layout()
        path = os.path.join(output_dir, f'pattern_{i+1:06d}.png')
        fig.savefig(path, dpi=100, bbox_inches='tight')
        plt.close(fig)

    print(f'[OK] Exported {patterns.shape[0]} PNG images to: {output_dir}/')


def main():
    parser = argparse.ArgumentParser(
        description='Visualize EMsoft EBSD synthetic patterns.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('data_path', nargs='?', default=None,
                        help='Path to EBSD .h5 file (default: prompt)')
    parser.add_argument('--output-dir', '-o', default=None,
                        help='Output directory for saved figures (default: same as data)')
    parser.add_argument('--grid', '-g', action='store_true',
                        help='Plot grid of all patterns')
    parser.add_argument('--single', '-s', type=int, metavar='N',
                        help='Plot pattern N (1-based) with intensity profiles')
    parser.add_argument('--compare', '-c', nargs=2, type=int, metavar=('N', 'M'),
                        help='Compare patterns N and M side-by-side')
    parser.add_argument('--heatmap', action='store_true',
                        help='Plot mean/std pixel statistics')
    parser.add_argument('--histogram', action='store_true',
                        help='Plot intensity histogram')
    parser.add_argument('--export-tiff', action='store_true',
                        help='Export all patterns as TIFF images')
    parser.add_argument('--export-png', action='store_true',
                        help='Export all patterns as PNG images')
    parser.add_argument('--all', '-a', action='store_true',
                        help='Run all visualizations')
    args = parser.parse_args()

    if args.data_path:
        data_path = args.data_path
    else:
        default = '/home/cosign/EMsoftData/Fe_FCC_exp/Fe_EBSD_patterns.h5'
        data_path = input(f'Enter path to EBSD HDF5 file [{default}]: ') or default
        if not os.path.exists(data_path):
            print(f'[ERROR] File not found: {data_path}')
            sys.exit(1)

    output_dir = args.output_dir
    if output_dir is None:
        output_dir = os.path.dirname(data_path)
    os.makedirs(output_dir, exist_ok=True)

    loader = EBSDDataLoader(data_path)
    print(f'\nLoaded: {loader}')
    print(f'  Patterns : {loader.patterns.shape}')
    print(f'  Euler    : {loader.euler_angles.shape}')
    print(f'  Strain   : {loader.deformation_tensors.shape if loader.deformation_tensors is not None else "not available"}')
    print()

    if args.all or (not any([args.grid, args.single is not None, args.compare,
                              args.heatmap, args.histogram, args.export_tiff, args.export_png])):
        args.grid = True
        args.single = 1
        args.heatmap = True
        args.histogram = True

    if args.grid:
        print('[*] Generating grid view...')
        plot_grid(loader,
                  output_path=os.path.join(output_dir, 'patterns_grid.png'))

    if args.single is not None:
        idx = max(0, min(args.single - 1, loader.patterns.shape[0] - 1))
        print(f'[*] Generating single pattern view (pattern #{args.single})...')
        plot_single_with_profiles(loader, idx=idx,
                                 output_path=os.path.join(output_dir, f'pattern_{args.single}_profile.png'))

    if args.compare is not None:
        idx1 = max(0, min(args.compare[0] - 1, loader.patterns.shape[0] - 1))
        idx2 = max(0, min(args.compare[1] - 1, loader.patterns.shape[0] - 1))
        print(f'[*] Comparing patterns #{args.compare[0]} and #{args.compare[1]}...')
        plot_pattern_difference(loader, idx1=idx1, idx2=idx2,
                                output_path=os.path.join(output_dir, 'pattern_comparison.png'))

    if args.heatmap:
        print('[*] Generating pixel statistics heatmap...')
        plot_pixel_statistics(loader,
                              output_path=os.path.join(output_dir, 'pixel_statistics.png'))

    if args.histogram:
        print('[*] Generating intensity histogram...')
        plot_intensity_histogram(loader,
                                  output_path=os.path.join(output_dir, 'intensity_histogram.png'))

    if args.export_tiff:
        print('[*] Exporting as TIFF...')
        export_as_tiff(loader, os.path.join(output_dir, 'tiff_exports'))

    if args.export_png:
        print('[*] Exporting as PNG...')
        export_as_png(loader, os.path.join(output_dir, 'png_exports'))

    print(f'\nAll outputs saved to: {output_dir}/')


if __name__ == '__main__':
    main()
